### ISSUE TITLE
RuntimeError: Could not determine platform.

### ISSUE THREAD

**Issue by songshuailin** [adafruit/Adafruit_SSD1306#227]
Traceback (most recent call last):
  File "oled.py", line 16, in <module>
    disp = Adafruit_SSD1306.SSD1306_128_32(rst=RST)
  File "/usr/local/lib/python3.8/dist-packages/Adafruit_SSD1306/SSD1306.py", line 287, in __init__
    super(SSD1306_128_32, self).__init__(128, 32, rst, dc, sclk, din, cs,
  File "/usr/local/lib/python3.8/dist-packages/Adafruit_SSD1306/SSD1306.py", line 85, in __init__
    self._gpio = GPIO.get_platform_gpio()
  File "/usr/local/lib/python3.8/dist-packages/Adafruit_GPIO/GPIO.py", line 426, in get_platform_gpio
    raise RuntimeError('Could not determine platform.')
RuntimeError: Could not determine platform.

**Comment by dhalbert** [comment]
You are using the https://github.com/adafruit/Adafruit_Python_SSD1306 library. That library is deprecated and no longer supported. Try using the https://github.com/adafruit/Adafruit_CircuitPython_SSD1306 library, which uses `adafruit-blinka` to allow CIrcuitPython code to run on your platform (if it is supported).
